### PR TITLE
Added ProfileScreen

### PR DESCRIPTION
**Pull request by BAChapin**
### Type of Change

- [x] Feature

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## How Can This PR Be Tested?

1.) Build and Run the application.
2.) Tap on the top right icon, which looks like a profile image.
3.) Confirm that the view looks as expected.
4.) Tap the Edit button on the Profile Image, select and test cropping a photo. Confirm that it works as expected.
5.) Once satisfied with the testing of this screen, tap the back button (or swipe back), and confirm the toolbar buttons look the same and do not have their tops clipped.

Simulator Screenshot - iPhone 15 Pro - 2024-06-25 at 22 34 33

**Test Configuration**:
* Firmware version: 17.5
* Hardware: iPhone 15 Pro
* Is Simulator:
  - [x] Yes
  - [ ] No

## Checklist:

- [x] Doc strings have been added to any public APIs
- [x] Appropriate tests have been added
- [x] The CHANGELOG.md file has been updated with your changes (1 entry per PR)
- [x] Before merging, rebase your branch with the target branch

### CODE REVIEW

**Comment by Michaelcraun** [comment]
@BAChapin since the other is merged, can we close this one, pls?

**Comment by BAChapin** [comment]
> @BAChapin since the other is merged, can we close this one, pls?

@Michaelcraun The other one? I'm not sure what you're referencing.

**Comment by Michaelcraun** [comment]
Oh, sorry, I was looking at the other Draft in the closed PRs... :/

**Comment by BAChapin** [comment]
@Michaelcraun Yeah, I think thats a simulator thing. Because I have that issue as well, but its ONLY with that image. I think it will need further testing on an actual device. Even before adding the cropping capability that photo shows up flipped.

**Comment by Michaelcraun** [comment]
> @Michaelcraun Yeah, I think thats a simulator thing. Because I have that issue as well, but its ONLY with that image. I think it will need further testing on an actual device. Even before adding the cropping capability that photo shows up flipped.

Hmm, I remember this being an actual problem with all images on a project back in my RED days, so I'm not 100% sure. I'll approve it for now, but we should definitely make sure this isn't happening before the final push.

**Review by Michaelcraun — APPROVED** [review]

**Pull request merged**
